[build]
  command = "pnpm --filter @saba/web build"
  publish = "apps/web/.next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_SITE_URL = "https://saba-cafe-demo.netlify.app"
  NEXT_PUBLIC_APP_DEEP_LINK = "saba://"
  NEXT_PUBLIC_GOOGLE_MAPS_EMBED_URL = "https://www.google.com/maps?q=Saba%20Cafe%2C%20152%20Old%20Kent%20Rd%2C%20London%20SE1%205TY&output=embed"
  GOOGLE_REVIEW_URL = "https://www.google.com/search?client=safari&hs=IG8U&sca_esv=fec7a8aac00c39eb&rls=en&sxsrf=ANbL-n4ZpGeld9tw7fL0GwdAaHONdRoQhQ:1777487607874&si=AL3DRZEsmMGCryMMFSHJ3StBhOdZ2-6yYkXd_doETEE1OR-qOTzBUoRnorFKgt2f9oRkUHQ5zoBJlX7BUwByjwVTUBTNED7Tlx0H_z0b8rhzVLecMRTU5UUV5fq-K33VmgA8wJWikWnb&q=Saba+Cafe+Reviews&sa=X&ved=2ahUKEwi-l9ar2ZOUAxXtUEEAHf6bKtIQ0bkNegQIMRAF&biw=1440&bih=820&dpr=2#"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
